RA-03 Make up navigation buttons
DenJavaExp/PizzaBurger pull request #3
Opened 2024-11-29 14:18 UTC by DenJavaExp

Задача

-Подключить в конфигурации проекта ViewBinding.
В методе onCreate() инициализировать переменную binding и передавать в setContentView(). -Реализовать фон основного лейаута в соответствии с цветом макета. -Основной контейнер сделать ConstraintLayout.
-Добавить контейнер для кнопок и спозиционировать к нижней части экрана. -Сверстать кнопки в лейауте activity_main.xml.
-Использовать стандартный рекомендуемый в документации тэг Button. -Учитывать отступы по бокам и между кнопками согласно макету. -Кнопки должны быть адаптивными по ширине (поместить кнопки в отдельный контейнер и использовать layout_weight в элементах). -Высоту кнопок сделать по размеру контента.
-Для реализации иконки на кнопке “Избранное” использовать атрибуты app:icon для добавления Drawable и app:iconGravity для ее позиционирования. -Импортировать в проект шрифт для кнопок.
-Определить шрифты, которые используются в макете и скачать их с Google Fonts. Обращать внимание на его толщину (в числовом и буквенном эквиваленте). -Создать каталог для шрифтов, импортировать 1 шрифт, задав имя через snake case. -Стилизовать кнопки, вынести в стили оформление текста кнопок. -Создать стиль с названием StyleTitle14 для текста и унаследовать (прописать родителя отдельным атрибутом) от TextAppearance.AppCompat. -Определить элементы: android:textSize, android:fontFamily, android:textAllCaps, android:textColor. -Создать стиль StyleNavButton, унаследовать от Widget.Material3.Button (так как тема по умолчанию наследуется от семейства Theme.Material3). -Определить все необходимые атрибуты. Без цвета фона, так как у каждой будет уникальный и прописывается непосредственно в верстке. Вынести в стиль следующие атрибуты: android:textAppearance — для определения созданного стиля текста. cornerRadius — для скругления углов кнопок.
Окрасить StatusBar и NavigationBar в соответствии с цветом макета. Вынести в ресурсы (и продолжать выносить все новые значения): Кастомный цвет.
Текст на кнопках.
Размеры основного отступа и половины от основного отступа (в ресурсный файл dimens.xml).

2024-11-30 18:12 UTC, Churickoid commented
Основной коммит с заданием ты сразу влил в мастер ветку. Гитхаб не даёт возможности оставлять комментарии в коде, которые не изменены в текущем Пулл Реквесте. Сделай git reset --hard на местер ветке с тем кодом и влей откатанную мастер ветку в гитхаб через  git push --force

2024-12-02 15:46 UTC, Churickoid requested changes

2024-12-02 15:46 UTC, Churickoid commented on app/src/main/res/layout/activity_main.xml
> +    android:background="#F5F5F5"
Все цвета мы выносим в ресурсы и ссылаемся на них их файла

2024-12-02 15:46 UTC, Churickoid commented on app/src/main/res/layout/activity_main.xml
> +            app:layout_constraintStart_toStartOf="parent" />
Этот параметр работает только для элементов constraintLayout, здесь он бесполезен. Тоже самое и для второй кнопки

2024-12-02 15:46 UTC, Churickoid commented on app/src/main/res/layout/activity_main.xml
> +            android:backgroundTint="@color/BackgroundCategoryButton"
Давай придерживаться одного стиля нейминга, везде snake_case используешь, но здесь camelCase

2024-12-02 15:46 UTC, Churickoid commented on app/src/main/res/layout/activity_main.xml
> +            android:background="@drawable/shape_button_footer"
Этот параметр общий для двух кнопок, его надо тоже вынести в стиль

2024-12-02 15:46 UTC, Churickoid commented on app/src/main/res/layout/activity_main.xml
> +            android:layout_marginStart="4dp"
У нас есть файл для цветов colors.xml и для строк strings.xml. По аналогии с ними в той же папки мы создали dimens.xml. Туда нужно вынести все цифровые значения, которые используются в вёрстке. Не только те, что требовались в задании. Например этот тоже

2024-12-02 15:46 UTC, Churickoid commented on app/src/main/res/layout/activity_main.xml
> +            android:paddingHorizontal="@dimen/main_indentation_favorites_category_buttons"
Эты параметры щас ничего не делают

2024-12-02 15:46 UTC, Churickoid commented on app/src/main/res/layout/activity_main.xml
> +        android:gravity="bottom"
По итогу тоже бесполезный параметр, ничего не делает сейчас

2024-12-02 15:46 UTC, Churickoid commented on app/src/main/res/layout/activity_main.xml
>      android:id="@+id/main"
Лучше в нейминге писать конкртено какой это объект верстки. Например constraint_layout_main или cl_main

2024-12-02 15:46 UTC, Churickoid commented on app/src/main/res/values/StyleNavButton.xml
> +</resources>
Отдельные файлы для стилей в данном случае создавать не надо. Пока у нас их немного, лучше писать всё в одном файле styles.xml

2024-12-02 15:46 UTC, Churickoid commented on app/src/main/res/values/styles.xml
> +        <item name="android:textSize">14sp</item>
Внутри стилей тоже надо выносить ресурсы в dimens

2024-12-02 15:46 UTC, Churickoid commented on app/src/main/java/com/example/pizzaburger/MainActivity.kt
> +    private var _bindig: ActivityMainBinding? = null
опечатка в нейминге

2024-12-03 16:21 UTC, Churickoid approved these changes
Молодец, по заданию всё верно! Поправь один коммент уже в следующем ПР

2024-12-03 16:21 UTC, Churickoid commented on app/src/main/res/values/styles.xml
> +        <dimen name="android:textSize">14sp</dimen>
этот параметр тоже нужно вынести в dimens

2024-12-03 16:25 UTC, Churickoid commented on app/src/main/res/values/styles.xml
> +        <dimen name="android:textSize">14sp</dimen>
Лучше настрой ПР только на одно условие - получить 1 апрув, а то закалебешься выполнять все эти условия

2024-12-04 18:16 UTC, ni032mas approved these changes

2024-12-04 18:16 UTC, merged