RA-05
DenJavaExp/PizzaBurger pull request #5
Opened 2024-12-13 08:49 UTC by DenJavaExp

2024-12-13 17:55 UTC, Churickoid requested changes

2024-12-13 17:55 UTC, aGroupoid commented on app/src/main/java/com/example/pizzaburger/MainActivity.kt
> +                replace<FavoritesFragment>(R.id.mainContainer)
В лямбды с транзакциями давай еще добавлять addToBackStack(null). Эта штука позволяет собирать фрагменты в стек, чтобы потом при многократном нажатии кнопки назад был пройден тот же путь. Только обратно. Когда будем внедрять Jetpack Navigation – оно будет там работать уже под капотом.
Сейчас при нажатии кнопки Назад на новом фрагменте - приложение закроется

2024-12-13 17:55 UTC, aGroupoid commented on app/src/main/java/com/example/pizzaburger/MainActivity.kt
> +            supportFragmentManager.commit {
Обращаю внимание на установку флага `setReorderingAllowed(true)`. В [документации](https://developer.android.com/guide/fragments/transactions#reordering) этому посвящен отдельный абзац. Флаг нужен для корректного выполнения транзакции.

2024-12-14 14:52 UTC, Churickoid approved these changes
Всё верно, молодец!

2024-12-14 14:59 UTC, merged